/**
 * build-lms-css — compile the student platform's stylesheet for one tour room.
 *
 * The LMS is Tailwind v3 with its own config and a global index.css full of
 * @apply rules; this site is Tailwind v4. Ported components only look like the
 * real product if their classes resolve against the LMS's own build, so each
 * room ships a precompiled copy: LMS base CSS (src/tour/lms-base, vendored from
 * fluentia-lms origin/main) + exactly the utilities that room's JSX uses, run
 * through autoprefixer (the LMS build has it; iOS needs -webkit-backdrop-filter).
 *
 * The output is committed, so the Vercel build never needs Tailwind v3.
 *
 * Run after changing any className in a room:
 *   node scripts/tour/build-lms-css.mjs unit
 *
 * Needs a local Tailwind v3 + postcss + autoprefixer; defaults to the LMS
 * checkout's node_modules (override with LMS_NODE_MODULES).
 */
import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { homedir } from "node:os";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const room = process.argv[2];
const ROOMS = ["unit", "grammar", "expressions", "verbs", "library"];
if (!ROOMS.includes(room)) {
  console.error(`usage: node scripts/tour/build-lms-css.mjs <${ROOMS.join("|")}>`);
  process.exit(1);
}

const NM = process.env.LMS_NODE_MODULES || join(homedir(), "projects/fluentia-lms/node_modules");
const bin = join(NM, ".bin/tailwindcss");
if (!existsSync(bin)) {
  console.error(`Tailwind v3 not found at ${bin} — set LMS_NODE_MODULES`);
  process.exit(1);
}

const out = join(ROOT, `src/tour/rooms/${room}/lms.generated.css`);
execFileSync(
  bin,
  [
    "-c", join(ROOT, "scripts/tour/lms-tailwind.config.js"),
    "-i", join(ROOT, "src/tour/lms-base/index.css"),
    "--content", join(ROOT, `src/tour/rooms/${room}/**/*.{js,jsx}`),
    "-o", out,
    "--minify",
  ],
  { stdio: ["ignore", "ignore", "inherit"], cwd: ROOT }
);

const postcss = (await import(pathToFileURL(join(NM, "postcss/lib/postcss.js")).href)).default;
const autoprefixer = (await import(pathToFileURL(join(NM, "autoprefixer/lib/autoprefixer.js")).href)).default;
const css = await readFile(out, "utf8");
const result = await postcss([autoprefixer({ overrideBrowserslist: ["iOS >= 15", "Safari >= 15", "last 2 Chrome versions", "last 2 Firefox versions"] })]).process(css, { from: undefined });
await writeFile(out, `/* GENERATED by scripts/tour/build-lms-css.mjs ${room} — do not edit by hand. */\n${result.css}`, "utf8");
console.log(`build-lms-css: ${room} → ${out.replace(ROOT + "/", "")} (${(result.css.length / 1024).toFixed(0)} KB)`);
