/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        navy: {
          50: '#e8ecf2',
          100: '#c5cede',
          200: '#9eafc7',
          300: '#7790b0',
          400: '#5a799f',
          500: '#3d628e',
          600: '#345681',
          700: '#294670',
          800: '#1a2d50',
          900: '#0a1225',
          950: '#060e1c',
        },
        sky: {
          50: '#e6f6fe',
          100: '#c0e8fc',
          200: '#96dafa',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#38bdf8',
          600: '#30aae4',
          700: '#2691cb',
          800: '#1d79b3',
          900: '#0e528a',
        },
        gold: {
          50: '#fef7e0',
          100: '#fdecb3',
          200: '#fce080',
          300: '#fbd44d',
          400: '#fbbf24',
          500: '#fbbf24',
          600: '#f5b020',
          700: '#ed9c1b',
          800: '#e58816',
          900: '#d9650d',
        },
        success: '#4ade80',
        error: '#ef4444',
        warning: '#f59e0b',
        muted: '#64748b',
        // New design system surface tokens
        'fl-surface': {
          void: 'var(--surface-void)',
          base: 'var(--surface-base)',
          raised: 'var(--surface-raised)',
          overlay: 'var(--surface-overlay)',
          interactive: 'var(--surface-interactive)',
        },
        'fl-glass': {
          card: 'var(--glass-card)',
          'card-hover': 'var(--glass-card-hover)',
          elevated: 'var(--glass-elevated)',
          input: 'var(--glass-input)',
        },
        'fl-border': {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
          focus: 'var(--border-focus)',
        },
        'fl-text': {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
        },
        'fl-accent': {
          sky: 'var(--accent-sky)',
          gold: 'var(--accent-gold)',
          violet: 'var(--accent-violet)',
          emerald: 'var(--accent-emerald)',
          rose: 'var(--accent-rose)',
        },
        atelier: {
          canvas:         '#0F0D0B',
          surface:        '#1A1612',
          elevated:       '#252019',
          ink:            '#F5EFE4',
          'ink-muted':    '#B5AA97',
          'ink-whisper':  '#6E6558',
          jewel:          '#14926A',
          'jewel-hover':  '#1DB07E',
          gold:           '#C9A464',
          rule:           'rgba(245, 239, 228, 0.06)',
        },
        // Backward compat aliases
        surface: 'var(--color-bg-surface)',
        'surface-raised': 'var(--color-bg-surface-raised)',
        'surface-overlay': 'var(--color-bg-overlay)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-medium': 'var(--color-border-medium)',
        darkest: 'var(--color-bg-base)',
        'theme': {
          'primary': 'var(--color-text-primary)',
          'secondary': 'var(--color-text-secondary)',
          'muted': 'var(--color-text-muted)',
          'card': 'var(--color-bg-surface)',
          'card-hover': 'var(--color-bg-hover)',
          'input': 'var(--color-bg-input)',
          'base': 'var(--color-bg-base)',
        },
      },
      fontFamily: {
        sans: ['Readex Pro', 'IBM Plex Sans Arabic', 'system-ui', 'sans-serif'],
        ar: ['Readex Pro', 'IBM Plex Sans Arabic', 'sans-serif'],
        'ar-hero': ['IBM Plex Sans Arabic', 'Readex Pro', 'sans-serif'],
        en: ['Inter Tight', 'Inter', 'system-ui', 'sans-serif'],
        num: ['Space Grotesk', 'Inter Tight', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Menlo', 'monospace'],
        tajawal: ['Tajawal', 'sans-serif'],
        playfair: ['Playfair Display', 'serif'],
        cormorant: ['"Cormorant Garamond"', 'Playfair Display', 'Georgia', 'serif'],
        inter: ['Inter', 'sans-serif'],
        'ibm-plex': ['IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'page-title': ['2rem', { lineHeight: '2.5rem', fontWeight: '700', letterSpacing: '-0.02em' }],
        'section-title': ['1.375rem', { lineHeight: '1.875rem', fontWeight: '600', letterSpacing: '-0.01em' }],
        'stat-number': ['2.5rem', { lineHeight: '1', fontWeight: '700', letterSpacing: '-0.02em' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      // MEGA-FIX V2 Phase D — z-index ladder via CSS variables.
      // After this, `z-popup`, `z-modal`, `z-toast`, etc. are available
      // as Tailwind utility classes that resolve at runtime via CSS vars.
      // Pair with src/styles/z-index.css for the variable declarations.
      zIndex: {
        'base':      'var(--z-base, 1)',
        'floor':     'var(--z-floor, 10)',
        'rise':      'var(--z-rise, 20)',
        'overlay':   'var(--z-overlay, 30)',
        'sidebar':   'var(--z-sidebar, 40)',
        'header':    'var(--z-header, 50)',
        'popup':     'var(--z-popup, 60)',
        'modal':     'var(--z-modal, 70)',
        'toast':     'var(--z-toast, 80)',
        'emergency': 'var(--z-emergency, 90)',
      },
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      boxShadow: {
        'soft': '0 4px 24px rgba(0,0,0,0.15)',
        'medium': '0 8px 32px rgba(0,0,0,0.25)',
        'elevated': '0 16px 48px rgba(0,0,0,0.35)',
        'glow-sky': 'var(--shadow-glow-sky)',
        'glow-gold': 'var(--shadow-glow-gold)',
        'glow-emerald': 'var(--shadow-glow-emerald)',
        'glow-violet': 'var(--shadow-glow-violet)',
        'glow-amber': '0 0 20px rgba(251,191,36,0.15)',
        'glow-rose': '0 0 20px rgba(251,113,133,0.15)',
        'inner-light': 'inset 0 1px 0 rgba(255,255,255,0.05)',
        'card': '0 4px 24px rgba(0,0,0,0.2)',
        'card-hover': '0 8px 32px rgba(0,0,0,0.3)',
        'inner-subtle': 'inset 0 1px 0 var(--color-card-inset)',
        'fl-xs': 'var(--shadow-xs)',
        'fl-sm': 'var(--shadow-sm)',
        'fl-md': 'var(--shadow-md)',
        'fl-lg': 'var(--shadow-lg)',
        'fl-xl': 'var(--shadow-xl)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      animation: {
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'fill-highlight': 'fill-highlight 0.6s ease-out',
        'fire-pulse': 'firePulse 1.5s ease-in-out infinite',
        'glow-breathe': 'glowBreathe 3s ease-in-out infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-in-up': 'fadeInUp 0.5s ease-out',
        'fade-in-down': 'fadeInDown 0.4s ease-out',
        'slide-in-right': 'slideInRight 0.4s ease-out',
        'slide-in-left': 'slideInLeft 0.4s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'bounce-in': 'bounceIn 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        'fill-highlight': {
          '0%': { boxShadow: '0 0 0 2px rgba(56,189,248,0.5)', borderColor: 'rgba(56,189,248,0.5)' },
          '100%': { boxShadow: '0 0 0 0 transparent', borderColor: 'var(--color-border-subtle)' },
        },
        firePulse: {
          '0%, 100%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '50%': { transform: 'scale(1.15)', filter: 'brightness(1.3)' },
        },
        glowBreathe: {
          '0%, 100%': { opacity: '0.5' },
          '50%': { opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(56,189,248,0.2)' },
          '100%': { boxShadow: '0 0 20px rgba(56,189,248,0.4)' },
        },
      },
      transitionTimingFunction: {
        'apple': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
