/**
 * cloudflare-routing — generate dist/_redirects, and prove that every route in
 * the router is accounted for by one of the three mechanisms Cloudflare Pages
 * gives us.
 *
 * WHY THIS EXISTS AT ALL — Cloudflare's _redirects is NOT Vercel's rewrites
 *   Vercel checks the filesystem FIRST and only then applies a rewrite, which is
 *   what lets vercel.json carry a bare `/(.*) → /app-shell.html` catch-all next
 *   to a dist/ full of real files. Cloudflare is the opposite: "Redirects are
 *   always followed, regardless of whether or not an asset matches the incoming
 *   request." A `/*` rule here would serve HTML for every file in /assets/ and
 *   every .webp under /tour/. So there is no catch-all in this file. Instead:
 *
 *   1. PRERENDERED routes need no rule at all. Pages already serves /about from
 *      dist/about.html — extension-less resolution is built in.
 *   2. CLIENT_ONLY_ROUTES get one explicit 200-rewrite each to the empty shell.
 *      They must NOT fall through to index.html, which now holds the homepage's
 *      prerendered markup: the homepage must never flash on /w.
 *   3. Everything unknown lands on dist/404.html, which is a copy of the empty
 *      shell. Same page the SPA already renders for an unknown path, now with a
 *      404 status instead of Vercel's 200 — which is the correct answer, and is
 *      also what keeps a deleted /assets/*.js chunk a 404 instead of an HTML
 *      body served as JavaScript.
 *
 *   /tour/* is the one case none of these three can express, because its client
 *   routes (/tour/unit/reading) and its media (/tour/unit/cover.webp) share a
 *   prefix. It is handled by functions/tour/[[path]].js.
 *
 * DRIFT IS A BUILD FAILURE, not a surprise in production: assertRouterClassified()
 * reads src/App.jsx and fails the build if a <Route> appears that is neither
 * prerendered, nor listed here, nor a redirect, nor the catch-all.
 */
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { PRERENDER_ROUTES } from "../src/content/seo.js";
import { WORK_HUB_PATH } from "../src/content/workEnglish.js";
import { prerenderedPaths } from "./sync-vercel-rewrites.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Routes the router owns that have NO prerendered .html twin. Each one gets an
 * explicit 200-rewrite to the empty shell.
 *
 * /w is the one that actually matters: it is the WhatsApp redirector handed out
 * in ads, so it must answer 200 with a working page, not a 404.
 */
export const CLIENT_ONLY_ROUTES = [
  "/atelier",
  "/aurora",
  "/partners/submitted",
  "/v1",
  "/v2",
  "/v4",
  "/v5",
  "/w",
];

/**
 * vercel.json's two host-independent redirects.
 *
 * 308, not 301: `"permanent": true` makes Vercel answer 308, and that is what
 * production serves today (measured, not assumed — curl on the live site).
 * 301 would let a client downgrade the follow-up request to GET; 308 forbids it.
 * Keeping the number identical is the whole point of a hosting move.
 */
export const REDIRECTS = [
  { from: "/test", to: "/level-test", status: 308 },
  { from: "/legacy", to: "/", status: 308 },
];

/**
 * Host-based redirects that vercel.json carries and Cloudflare Pages CANNOT:
 * `_redirects` has no host matching. Recorded here so the gap is written down
 * rather than remembered.
 *   fluentia.online/*        → https://fluentia.academy/*
 *   fluentia-site.vercel.app → https://fluentia.academy/*  (dies with Vercel anyway)
 * fluentia.online is a separate zone still on Vercel's nameservers; it needs a
 * Cloudflare Redirect Rule on its own zone BEFORE the Vercel project is deleted.
 */
export const UNPORTABLE_HOST_REDIRECTS = [
  { host: "fluentia.online", to: "https://fluentia.academy" },
  { host: "fluentia-site.vercel.app", to: "https://fluentia.academy" },
];

export function cloudflareRedirectsFile() {
  const lines = [
    "# Generated by scripts/cloudflare-routing.mjs — do not hand-edit.",
    "# There is deliberately NO catch-all: Cloudflare follows a redirect rule even",
    "# when a real asset matches, so /* would serve HTML for /assets/*.js.",
    "# Unknown paths land on 404.html, which is a copy of the empty app shell.",
    "",
    "# — redirects (vercel.json parity) —",
    ...REDIRECTS.map((r) => `${r.from}  ${r.to}  ${r.status}`),
    "",
    "# — client-only routes: the EMPTY shell, never index.html (homepage markup) —",
    "# Target is /app-shell, NOT /app-shell.html. Measured on wrangler pages dev:",
    "# Pages redirects every .html URL to its extension-less form, and it does that",
    "# to a REWRITE target too — so `/w /app-shell.html 200` answered 308 Location:",
    "# /app-shell and the router then saw /app-shell instead of /w. Extension-less",
    "# resolves to app-shell.html and serves it at the original URL with 200.",
    ...CLIENT_ONLY_ROUTES.map((p) => `${p}  /app-shell  200`),
    "",
  ];
  return `${lines.join("\n")}\n`;
}

/** Every <Route path="..."> in App.jsx, in source order. */
async function routerPaths() {
  const app = await readFile(join(ROOT, "src", "App.jsx"), "utf8");
  return [...app.matchAll(/<Route\s+path="([^"]*)"/g)].map((m) => m[1]);
}

/**
 * Fail the build if the router grew a route nobody routes to on the new host.
 * A prerendered route, a listed client-only route, a redirect source, a
 * :param route (covered by its prerendered twins, then 404.html) and the "*"
 * catch-all are all fine. Anything else is a page that would 404 in production.
 */
export async function assertRouterClassified() {
  const prerendered = new Set([...prerenderedPaths(), "/", WORK_HUB_PATH, ...PRERENDER_ROUTES]);
  const clientOnly = new Set(CLIENT_ONLY_ROUTES);
  const redirected = new Set(REDIRECTS.map((r) => r.from));

  const unclassified = (await routerPaths()).filter((p) => {
    if (p === "*" || p.includes(":")) return false;
    return !prerendered.has(p) && !clientOnly.has(p) && !redirected.has(p);
  });

  if (unclassified.length) {
    throw new Error(
      `cloudflare-routing: ${unclassified.length} route(s) in src/App.jsx are not routed on Cloudflare Pages:\n` +
        unclassified.map((p) => `  ${p}`).join("\n") +
        "\n\nAdd each to CLIENT_ONLY_ROUTES (serves the empty shell at 200) or to\n" +
        "PRERENDER_ROUTES in src/content/seo.js (gets its own .html with real meta),\n" +
        "in scripts/cloudflare-routing.mjs.",
    );
  }
  return true;
}
